// Generated by CoffeeScript 1.3.3
(function() {

  describe("TimeEntry", function() {
    beforeEach(function() {
      return this.entry = new TimeEntry('2.5h Coca Cola - changed color to green');
    });
    return it("extracts title", function() {
      return expect(this.entry.title).toEqual('Coca Cola');
    });
  });

}).call(this);
